"use client";

import { useEffect, useState } from "react";
import * as api from "../api";
import { Collection, cx } from "../data";
import { Card, Code, Label, Mono } from "../ui/kit";

type Lang = "python" | "javascript" | "curl";

const LANGS: { id: Lang; label: string }[] = [
  { id: "python", label: "Python" },
  { id: "javascript", label: "JavaScript" },
  { id: "curl", label: "curl" },
];

/** SDK & docs.
 *
 *  The snippets are generated by the server for the selected collection, so
 *  the two details a person always has to change — which collection and which
 *  host — are already correct. The key is never interpolated: a snippet gets
 *  pasted into chat and tickets, so it reads the key from the environment. */
export function Sdk({ collections }: { collections: Collection[] }) {
  const [collectionId, setCollectionId] = useState(collections[0]?.id || "default");
  const [lang, setLang] = useState<Lang>("python");
  const [payload, setPayload] = useState<api.Snippets | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let live = true;
    setPayload(null);
    api
      .snippets(collectionId)
      .then((s) => live && setPayload(s))
      .catch((e) => live && setError((e as Error).message));
    return () => {
      live = false;
    };
  }, [collectionId]);

  return (
    <div className="px-6 py-6">
      <div className="mb-5">
        <h1 className="text-base font-semibold text-ink">SDK &amp; docs</h1>
        <p className="mt-1 max-w-xl text-xs leading-relaxed text-subtle">
          Ready to paste, already pointed at your collection. Create a key first, then put
          it in <Mono className="text-accentSoft">{payload?.key_env || "KB_API_KEY"}</Mono> —
          the snippet reads it from there rather than carrying it.
        </p>
      </div>

      <div className="mb-4 flex flex-wrap items-center gap-3">
        <div className="flex items-center gap-2">
          <Label>collection</Label>
          <select
            value={collectionId}
            onChange={(e) => setCollectionId(e.target.value)}
            className="rounded-lg border border-edge bg-canvas px-2.5 py-1.5 font-mono text-2xs text-ink outline-none focus:border-accent/60"
          >
            {collections.map((c) => (
              <option key={c.id} value={c.id}>
                {c.id}
              </option>
            ))}
          </select>
        </div>
        <div className="flex gap-1 rounded-lg border border-edge bg-elevated p-0.5">
          {LANGS.map((l) => (
            <button
              key={l.id}
              onClick={() => setLang(l.id)}
              className={cx(
                "rounded-md px-3 py-1 font-mono text-2xs transition",
                lang === l.id ? "bg-accent/15 text-ink" : "text-subtle hover:text-muted"
              )}
            >
              {l.label}
            </button>
          ))}
        </div>
      </div>

      {error && (
        <p className="rounded-lg border border-danger/30 bg-danger/10 px-3 py-2 font-mono text-2xs text-danger">
          {error}
        </p>
      )}

      {!payload ? (
        <div className="font-mono text-xs text-subtle">Loading snippets…</div>
      ) : (
        <div className="space-y-4">
          {payload.install[lang] && (
            <div>
              <Label className="mb-2 block">install</Label>
              <Code code={payload.install[lang] as string} filename="shell" />
            </div>
          )}

          <div>
            <Label className="mb-2 block">write, then read</Label>
            <Code code={payload.snippets[lang]} filename={lang} />
          </div>

          <Card className="p-4">
            <Label className="mb-2 block">endpoint</Label>
            <Mono className="text-xs text-muted">{payload.base_url}</Mono>
            <p className="mt-2 text-2xs leading-relaxed text-subtle">
              Every call is scoped by the key it carries, so no request names a workspace.
              A collection travels as the <Mono>X-Collection</Mono> header.
            </p>
          </Card>
        </div>
      )}
    </div>
  );
}
